name: learn-github-action
run-name: ${{ github.actor}} is learning GitHub Actions
on: [push]
jobs: 
  check-bats-version: 
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/steup-node@v3
        with: 
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v